"""Prepare and persist the ignored local state for the add-companion demo."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import tempfile
from typing import Any
from urllib.parse import quote


LAB = Path(__file__).resolve().parents[2]
DEFAULT_ENV = LAB / ".env"
DEFAULT_EVIDENCE = LAB / "evidence" / "demos" / "01-add-companion"
PLATFORM = "GoogleVertexAI"
COMPANION_PREFIX = "agent-governance:companion:v1:gcp:"
ASSIGNMENT_MODE = "dedicated"
LAB_GROUPING_POLICY_VERSION = "lab-20-dedicated-default-v1"
LAB_APPROVAL_REFERENCE = "lab-20-disposable-demo-gate"


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain one JSON object")
    return value


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$", line)
        if match:
            values[match.group(1)] = match.group(2).strip()
    return values


def update_env(path: Path, updates: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    remaining = dict(updates)
    updated_keys: set[str] = set()
    updated: list[str] = []

    for line in lines:
        match = re.match(r"(\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*)=(.*)$", line)
        if match and match.group(2) in updates:
            key = match.group(2)
            if key in updated_keys:
                continue
            updated.append(f"{match.group(1)}{key}{match.group(3)}={updates[key]}")
            updated_keys.add(key)
            remaining.pop(key, None)
        else:
            updated.append(line)

    if remaining:
        if updated and updated[-1]:
            updated.append("")
        updated.append("# Generated by demos/01-add-companion/prepare_demo.py")
        updated.extend(f"{key}={value}" for key, value in remaining.items())

    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f"{path.name}.", suffix=".tmp", text=True
    )
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as temporary:
            temporary.write("\n".join(updated) + "\n")
        os.replace(temporary_name, path)
    except Exception:
        Path(temporary_name).unlink(missing_ok=True)
        raise


def package_entries(package_lists: list[dict[str, Any]]) -> list[dict[str, Any]]:
    packages: list[dict[str, Any]] = []
    for index, package_list in enumerate(package_lists, start=1):
        page = package_list.get("value")
        if not isinstance(page, list):
            raise ValueError(
                f"Package List page {index} must contain a value array"
            )
        packages.extend(package for package in page if isinstance(package, dict))
    return packages


def package_platform_counts(
    package_lists: list[dict[str, Any]],
) -> dict[str, int]:
    counts: dict[str, int] = {}
    for package in package_entries(package_lists):
        platform = package.get("platform")
        label = platform if isinstance(platform, str) and platform else "<missing>"
        counts[label] = counts.get(label, 0) + 1
    return counts


def package_values(
    package_lists: list[dict[str, Any]], target_name: str
) -> dict[str, str]:
    matches = [
        package
        for package in package_entries(package_lists)
        if package.get("displayName") == target_name
        and package.get("platform") == PLATFORM
    ]
    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one {PLATFORM} Package named {target_name!r}; "
            f"found {len(matches)}"
        )
    package_id = matches[0].get("id")
    if not isinstance(package_id, str) or not package_id:
        raise ValueError("Selected Package has no id")
    return {"A365_DEMO_ORIGINAL_PACKAGE_ID": package_id}


def source_values(package: dict[str, Any], target_name: str) -> dict[str, str]:
    if package.get("displayName") != target_name:
        raise ValueError("Package Details displayName does not match A365_DEMO_TARGET_NAME")
    if package.get("platform") != PLATFORM:
        raise ValueError(f"Selected Package is not from {PLATFORM}")
    if package.get("agentIdentityId"):
        raise ValueError("Original Registry Sync Package already has an Agent Identity")

    definitions: list[dict[str, Any]] = []
    for detail in package.get("elementDetails") or []:
        if not isinstance(detail, dict):
            continue
        for element in detail.get("elements") or []:
            if not isinstance(element, dict):
                continue
            raw_definition = element.get("definition")
            if not isinstance(raw_definition, str):
                continue
            try:
                definition = json.loads(raw_definition)
            except json.JSONDecodeError:
                continue
            source_ids = definition.get("SourceIds")
            if (
                isinstance(source_ids, dict)
                and source_ids.get("mac.agentRegistrationType") == "ConnectedPlatform"
                and source_ids.get("mac.agentRegistrationProviderType") == PLATFORM
            ):
                definitions.append(definition)

    if len(definitions) != 1:
        raise ValueError(
            f"Expected exactly one Connected Platform {PLATFORM} definition; "
            f"found {len(definitions)}"
        )

    definition = definitions[0]
    required = {
        "A365_DEMO_PROVIDER_SOURCE_AGENT_ID": "SourceAgentId",
        "A365_DEMO_SOURCE_CREATED_AT": "CreatedDateTime",
        "A365_DEMO_SOURCE_MODIFIED_AT": "LastModifiedDateTime",
    }
    values = {"A365_DEMO_ORIGINAL_PACKAGE_ID": package.get("id")}
    for env_key, source_key in required.items():
        value = definition.get(source_key)
        if not isinstance(value, str) or not value:
            raise ValueError(f"Selected source has no {source_key}")
        values[env_key] = value
    if not isinstance(values["A365_DEMO_ORIGINAL_PACKAGE_ID"], str):
        raise ValueError("Package Details has no id")
    return values


def assignment_values(env: dict[str, str], provider_source: str) -> dict[str, str]:
    tenant_id = env.get("A365_TENANT_ID", "")
    if not tenant_id:
        raise ValueError("Set A365_TENANT_ID before preparing the assignment")

    canonical_key = f"{tenant_id}|{PLATFORM}|{provider_source}"
    digest = hashlib.sha256(canonical_key.encode("utf-8")).hexdigest()[:16]
    return {
        "A365_DEMO_ASSIGNMENT_MODE": ASSIGNMENT_MODE,
        "A365_DEMO_BLUEPRINT_GROUP": f"dedicated-gcp-{digest}",
        "A365_DEMO_GROUPING_POLICY_VERSION": LAB_GROUPING_POLICY_VERSION,
        "A365_DEMO_APPROVAL_REFERENCE": LAB_APPROVAL_REFERENCE,
    }


def blueprint_values(
    blueprint: dict[str, Any], existing_object_id: str = ""
) -> dict[str, str]:
    object_id = blueprint.get("id")
    app_id = blueprint.get("appId")
    if not isinstance(object_id, str) or not object_id:
        raise ValueError("Blueprint response has no object id")
    if not isinstance(app_id, str) or not app_id:
        raise ValueError("Blueprint response has no appId")
    if existing_object_id and object_id != existing_object_id:
        raise ValueError(
            "Blueprint response does not match A365_DEMO_BLUEPRINT_OBJECT_ID"
        )
    return {
        "A365_DEMO_BLUEPRINT_OBJECT_ID": object_id,
        "A365_DEMO_BLUEPRINT_APP_ID": app_id,
    }


def registration_values(
    registration: dict[str, Any], provider_source: str
) -> dict[str, str]:
    registration_id = registration.get("id")
    source_agent_id = registration.get("sourceAgentId")
    if not isinstance(registration_id, str) or not registration_id:
        raise ValueError("Registration response has no id")
    values = {
        "A365_DEMO_COMPANION_REGISTRATION_ID": registration_id,
        "A365_DEMO_COMPANION_REGISTRATION_ID_PATH": quote(
            registration_id, safe=""
        ),
    }
    if source_agent_id is not None:
        expected_source = COMPANION_PREFIX + provider_source
        if source_agent_id != expected_source:
            raise ValueError("Registration source does not match the selected Package")
        values["A365_DEMO_COMPANION_SOURCE_AGENT_ID"] = source_agent_id
    return values


def mapping_values(
    env: dict[str, str],
    blueprint: dict[str, Any],
    principal: dict[str, Any],
    identity: dict[str, Any],
    registration: dict[str, Any],
    companion_package: dict[str, Any],
) -> dict[str, Any]:
    blueprint_object_id = env.get("A365_DEMO_BLUEPRINT_OBJECT_ID", "")
    blueprint_app_id = blueprint.get("appId")
    principal_id = principal.get("id")
    identity_id = identity.get("id")
    registration_id = registration.get("id")
    companion_package_id = companion_package.get("id")
    provider_source = env.get("A365_DEMO_PROVIDER_SOURCE_AGENT_ID", "")
    expected_assignment = assignment_values(env, provider_source)

    if (
        blueprint.get("id") != blueprint_object_id
        or not blueprint_app_id
        or blueprint_app_id != env.get("A365_DEMO_BLUEPRINT_APP_ID")
    ):
        raise ValueError("Blueprint response does not match A365_DEMO_BLUEPRINT_OBJECT_ID")
    if (
        not principal_id
        or principal.get("appId") != blueprint_app_id
        or principal.get("accountEnabled") is False
    ):
        raise ValueError("Blueprint principal is missing, mismatched, or disabled")
    if (
        not identity_id
        or identity.get("agentIdentityBlueprintId") != blueprint_app_id
        or identity.get("servicePrincipalType") != "ServiceIdentity"
    ):
        raise ValueError("Agent Identity does not belong to the selected Blueprint")
    if not registration_id:
        raise ValueError("Registration response has no id")
    if registration.get("sourceAgentId") != COMPANION_PREFIX + provider_source:
        raise ValueError("Registration has an unexpected companion sourceAgentId")
    if registration.get("originatingStore") != PLATFORM:
        raise ValueError(f"Registration originatingStore is not {PLATFORM}")
    if (
        registration.get("agentIdentityBlueprintId") != blueprint_app_id
        or registration.get("agentIdentityId") != identity_id
    ):
        raise ValueError("Registration identity links do not match the created objects")
    if (
        not companion_package_id
        or companion_package_id != env.get("A365_DEMO_COMPANION_PACKAGE_ID")
        or companion_package.get("platform") != PLATFORM
        or companion_package.get("agentIdentityId") != identity_id
    ):
        raise ValueError("Companion Package does not match the mapped identity")

    companion_definitions: list[dict[str, Any]] = []
    for detail in companion_package.get("elementDetails") or []:
        if not isinstance(detail, dict):
            continue
        for element in detail.get("elements") or []:
            if not isinstance(element, dict):
                continue
            raw_definition = element.get("definition")
            if not isinstance(raw_definition, str):
                continue
            try:
                definition = json.loads(raw_definition)
            except json.JSONDecodeError:
                continue
            if definition.get("SourceAgentId") == registration.get("sourceAgentId"):
                companion_definitions.append(definition)

    if len(companion_definitions) != 1:
        raise ValueError(
            "Companion Package does not contain one matching source definition"
        )
    companion_definition = companion_definitions[0]
    if (
        companion_definition.get("AgentIdentityBlueprintId") != blueprint_app_id
        or companion_definition.get("AgentIdentityId") != identity_id
    ):
        raise ValueError("Companion Package identity links do not match the mapping")
    if (
        env.get("A365_DEMO_ASSIGNMENT_MODE")
        != expected_assignment["A365_DEMO_ASSIGNMENT_MODE"]
        or env.get("A365_DEMO_BLUEPRINT_GROUP")
        != expected_assignment["A365_DEMO_BLUEPRINT_GROUP"]
    ):
        raise ValueError("Saved assignment does not match the scoped provider source")

    package_display_name = env["A365_DEMO_TARGET_NAME"]
    expected_blueprint_name = (
        f"{package_display_name} - dedicated disposable Blueprint"
    )
    expected_identity_name = f"{package_display_name} - managed Agent Identity"
    expected_companion_name = f"{package_display_name} - managed companion"
    observed_names = {
        "blueprintDisplayName": blueprint.get("displayName"),
        "blueprintPrincipalDisplayName": principal.get("displayName"),
        "agentIdentityDisplayName": identity.get("displayName"),
        "companionRegistrationDisplayName": registration.get("displayName"),
        "companionPackageDisplayName": companion_package.get("displayName"),
    }
    expected_names = {
        "blueprintDisplayName": expected_blueprint_name,
        "blueprintPrincipalDisplayName": expected_blueprint_name,
        "agentIdentityDisplayName": expected_identity_name,
        "companionRegistrationDisplayName": expected_companion_name,
        "companionPackageDisplayName": expected_companion_name,
    }
    missing_names = [
        key for key, value in observed_names.items()
        if not isinstance(value, str) or not value
    ]
    if missing_names:
        raise ValueError(
            "Mapped objects are missing display names: " + ", ".join(missing_names)
        )
    if observed_names != expected_names:
        raise ValueError("Created object display names do not match the naming policy")

    return {
        "platform": PLATFORM,
        "assignmentMode": env["A365_DEMO_ASSIGNMENT_MODE"],
        "blueprintGroup": env["A365_DEMO_BLUEPRINT_GROUP"],
        "groupingPolicyVersion": env["A365_DEMO_GROUPING_POLICY_VERSION"],
        "approvalReference": env["A365_DEMO_APPROVAL_REFERENCE"],
        "members": [provider_source],
        "packageDisplayName": package_display_name,
        **observed_names,
        "status": "active",
        "nameSyncStatus": "in-sync",
        "sourceLastModifiedDateTime": env["A365_DEMO_SOURCE_MODIFIED_AT"],
        "lastObservedAt": datetime.now(timezone.utc).isoformat(),
        "providerSourceAgentId": provider_source,
        "packageId": env["A365_DEMO_ORIGINAL_PACKAGE_ID"],
        "companionSourceAgentId": registration["sourceAgentId"],
        "companionRegistrationId": registration_id,
        "companionPackageId": companion_package_id,
        "blueprintObjectId": blueprint_object_id,
        "blueprintId": blueprint_app_id,
        "blueprintPrincipalId": principal_id,
        "agentIdentityId": identity_id,
    }


def select_command(args: argparse.Namespace) -> None:
    env = read_env(args.env)
    target_name = env.get("A365_DEMO_TARGET_NAME", "")
    if not target_name:
        raise ValueError("Set A365_DEMO_TARGET_NAME before running select")
    pages = [load_json(path) for path in args.package_list]
    counts = package_platform_counts(pages)
    summary = ", ".join(
        f"{platform}={count}" for platform, count in sorted(counts.items())
    )
    print(f"Observed Package counts by platform: {summary or 'none'}")
    updates = package_values(pages, target_name)
    update_env(args.env, updates)
    print("Updated A365_DEMO_ORIGINAL_PACKAGE_ID in the ignored .env")


def prepare_command(args: argparse.Namespace) -> None:
    env = read_env(args.env)
    target_name = env.get("A365_DEMO_TARGET_NAME", "")
    if not target_name:
        raise ValueError("Set A365_DEMO_TARGET_NAME before running prepare")
    updates = source_values(load_json(args.package_details), target_name)
    updates.update(
        assignment_values(env, updates["A365_DEMO_PROVIDER_SOURCE_AGENT_ID"])
    )
    update_env(args.env, updates)
    print(
        "Updated the Package and source fields and generated the dedicated "
        "Blueprint assignment in the ignored .env"
    )


def blueprint_command(args: argparse.Namespace) -> None:
    env = read_env(args.env)
    provider_source = env.get("A365_DEMO_PROVIDER_SOURCE_AGENT_ID", "")
    if not provider_source:
        raise ValueError("Prepare the selected Package before resolving a Blueprint")
    expected_assignment = assignment_values(env, provider_source)
    if (
        env.get("A365_DEMO_ASSIGNMENT_MODE")
        != expected_assignment["A365_DEMO_ASSIGNMENT_MODE"]
        or env.get("A365_DEMO_BLUEPRINT_GROUP")
        != expected_assignment["A365_DEMO_BLUEPRINT_GROUP"]
    ):
        raise ValueError("Generated dedicated assignment is missing or mismatched")
    updates = blueprint_values(
        load_json(args.blueprint),
        env.get("A365_DEMO_BLUEPRINT_OBJECT_ID", ""),
    )
    update_env(args.env, updates)
    print(
        "Updated A365_DEMO_BLUEPRINT_OBJECT_ID and "
        "A365_DEMO_BLUEPRINT_APP_ID in the ignored .env"
    )


def registration_command(args: argparse.Namespace) -> None:
    env = read_env(args.env)
    provider_source = env.get("A365_DEMO_PROVIDER_SOURCE_AGENT_ID", "")
    if not provider_source:
        raise ValueError("Prepare the selected Package before the Registration")
    updates = registration_values(load_json(args.registration), provider_source)
    update_env(args.env, updates)
    if "A365_DEMO_COMPANION_SOURCE_AGENT_ID" in updates:
        print(
            "Updated the verified companion source, raw Registration ID, "
            "and path-safe Registration ID"
        )
    else:
        print(
            "Updated the raw and path-safe Registration IDs; "
            "verify the Registration next"
        )


def finalize_command(args: argparse.Namespace) -> None:
    env = read_env(args.env)
    required_env = (
        "A365_DEMO_TARGET_NAME",
        "A365_DEMO_ORIGINAL_PACKAGE_ID",
        "A365_DEMO_PROVIDER_SOURCE_AGENT_ID",
        "A365_DEMO_ASSIGNMENT_MODE",
        "A365_DEMO_BLUEPRINT_GROUP",
        "A365_DEMO_GROUPING_POLICY_VERSION",
        "A365_DEMO_APPROVAL_REFERENCE",
        "A365_DEMO_BLUEPRINT_OBJECT_ID",
        "A365_DEMO_BLUEPRINT_APP_ID",
        "A365_DEMO_COMPANION_PACKAGE_ID",
    )
    missing = [key for key in required_env if not env.get(key)]
    if missing:
        raise ValueError(f"Missing required .env values: {', '.join(missing)}")

    mapping = mapping_values(
        env,
        load_json(args.blueprint),
        load_json(args.principal),
        load_json(args.identity),
        load_json(args.registration),
        load_json(args.companion_package),
    )
    updates = {
        "A365_DEMO_BLUEPRINT_APP_ID": mapping["blueprintId"],
        "A365_DEMO_BLUEPRINT_PRINCIPAL_ID": mapping["blueprintPrincipalId"],
        "A365_DEMO_AGENT_IDENTITY_ID": mapping["agentIdentityId"],
        "A365_DEMO_COMPANION_SOURCE_AGENT_ID": mapping["companionSourceAgentId"],
        "A365_DEMO_COMPANION_REGISTRATION_ID": mapping[
            "companionRegistrationId"
        ],
        "A365_DEMO_COMPANION_REGISTRATION_ID_PATH": quote(
            mapping["companionRegistrationId"], safe=""
        ),
    }
    update_env(args.env, updates)
    args.mapping.parent.mkdir(parents=True, exist_ok=True)
    args.mapping.write_text(json.dumps(mapping, indent=2) + "\n", encoding="utf-8")
    print("Saved the ignored durable mapping and refreshed generated IDs")


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser()
    result.add_argument("--env", type=Path, default=DEFAULT_ENV)
    commands = result.add_subparsers(dest="command", required=True)

    select = commands.add_parser("select")
    select.add_argument(
        "--package-list",
        type=Path,
        nargs="+",
        default=[DEFAULT_EVIDENCE / "package-list.json"],
    )
    select.set_defaults(func=select_command)

    prepare = commands.add_parser("prepare")
    prepare.add_argument(
        "--package-details",
        type=Path,
        default=DEFAULT_EVIDENCE / "package-details.json",
    )
    prepare.set_defaults(func=prepare_command)

    blueprint = commands.add_parser("blueprint")
    blueprint.add_argument(
        "--blueprint", type=Path, default=DEFAULT_EVIDENCE / "blueprint.json"
    )
    blueprint.set_defaults(func=blueprint_command)

    registration = commands.add_parser("registration")
    registration.add_argument(
        "--registration",
        type=Path,
        default=DEFAULT_EVIDENCE / "companion-registration.json",
    )
    registration.set_defaults(func=registration_command)

    finalize = commands.add_parser("finalize")
    finalize.add_argument(
        "--blueprint", type=Path, default=DEFAULT_EVIDENCE / "blueprint.json"
    )
    finalize.add_argument(
        "--identity",
        type=Path,
        default=DEFAULT_EVIDENCE / "agent-identity.json",
    )
    finalize.add_argument(
        "--principal",
        type=Path,
        default=DEFAULT_EVIDENCE / "blueprint-principal.json",
    )
    finalize.add_argument(
        "--registration",
        type=Path,
        default=DEFAULT_EVIDENCE / "companion-registration.json",
    )
    finalize.add_argument(
        "--companion-package",
        type=Path,
        default=DEFAULT_EVIDENCE / "companion-package-after-create.json",
    )
    finalize.add_argument(
        "--mapping", type=Path, default=DEFAULT_EVIDENCE / "mapping.json"
    )
    finalize.set_defaults(func=finalize_command)
    return result


def main() -> None:
    args = parser().parse_args()
    try:
        args.func(args)
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as error:
        raise SystemExit(f"Preparation failed: {error}") from error


if __name__ == "__main__":
    main()
